function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 2; // obj_main
	global.__objectDepths[1] = 0; // obj_starting_grid
	global.__objectDepths[2] = 10; // obj_path
	global.__objectDepths[3] = 0; // obj_path_point_controller
	global.__objectDepths[4] = -100; // obj_left_path
	global.__objectDepths[5] = 0; // obj_solid
	global.__objectDepths[6] = 0; // obj_block
	global.__objectDepths[7] = 1; // obj_tread
	global.__objectDepths[8] = -1; // obj_wheel
	global.__objectDepths[9] = 0; // obj_car
	global.__objectDepths[10] = 0; // obj_parent_player
	global.__objectDepths[11] = 0; // obj_parent_ai
	global.__objectDepths[12] = 0; // obj_sportscar
	global.__objectDepths[13] = 0; // obj_rallycar
	global.__objectDepths[14] = 0; // obj_racingcar
	global.__objectDepths[15] = 0; // obj_motorbike
	global.__objectDepths[16] = 0; // obj_go_kart
	global.__objectDepths[17] = 0; // obj_AG_ship
	global.__objectDepths[18] = 0; // obj_truck
	global.__objectDepths[19] = 0; // obj_tank
	global.__objectDepths[20] = 0; // obj_ai_sportscar1
	global.__objectDepths[21] = 0; // obj_ai_sportscar2
	global.__objectDepths[22] = 0; // obj_ai_sportscar3
	global.__objectDepths[23] = 0; // obj_ai_sportscar4
	global.__objectDepths[24] = 0; // obj_ai_racingcar_parent
	global.__objectDepths[25] = 0; // obj_ai_racingcar1
	global.__objectDepths[26] = 0; // obj_ai_racingcar2
	global.__objectDepths[27] = 0; // obj_ai_racingcar3
	global.__objectDepths[28] = 0; // obj_ai_racingcar4
	global.__objectDepths[29] = 0; // obj_ai_motorbike1
	global.__objectDepths[30] = 0; // obj_ai_go_kart1
	global.__objectDepths[31] = 0; // obj_ai_AG_ship1
	global.__objectDepths[32] = 0; // obj_ai_truck1
	global.__objectDepths[33] = 0; // obj_ai_rallycar1
	global.__objectDepths[34] = 0; // obj_ai_tank1
	global.__objectDepths[35] = 10; // obj_colour_ai
	global.__objectDepths[36] = -30; // obj_target
	global.__objectDepths[37] = 0; // obj_draw_checkpoint_car
	global.__objectDepths[38] = 0; // obj_draw_checkpoint_ai_yellow
	global.__objectDepths[39] = -50; // obj_car_pathPos
	global.__objectDepths[40] = -50; // obj_ai_yellow_pathPos
	global.__objectDepths[41] = -5000; // obj_debug_messages
	global.__objectDepths[42] = -100000; // obj_GUI
	global.__objectDepths[43] = 0; // obj_camera
	global.__objectDepths[44] = -500; // obj_teleport
	global.__objectDepths[45] = -100; // obj_teleport_target
	global.__objectDepths[46] = -150; // obj_start_lights
	global.__objectDepths[47] = -1000000; // obj_race_start
	global.__objectDepths[48] = -20; // obj_explosion
	global.__objectDepths[49] = -20; // obj_smoke
	global.__objectDepths[50] = 0; // obj_car_select_header
	global.__objectDepths[51] = 0; // obj_game_version
	global.__objectDepths[52] = 0; // obj_game_information
	global.__objectDepths[53] = 0; // obj_rallycar_option
	global.__objectDepths[54] = 0; // obj_go_kart_option
	global.__objectDepths[55] = 0; // obj_motorbike_option
	global.__objectDepths[56] = 0; // obj_racingcar_option
	global.__objectDepths[57] = 0; // obj_truck_option
	global.__objectDepths[58] = 0; // obj_AG_ship_option
	global.__objectDepths[59] = 0; // obj_sportscar_option
	global.__objectDepths[60] = 0; // obj_tank_option
	global.__objectDepths[61] = 0; // obj_cs_menu_control
	global.__objectDepths[62] = 0; // obj_room_controller
	global.__objectDepths[63] = -1; // obj_continue
	global.__objectDepths[64] = -1; // obj_restart
	global.__objectDepths[65] = -1; // obj_exit
	global.__objectDepths[66] = -1; // obj_pause_header
	global.__objectDepths[67] = 0; // obj_pause_menu_controller
	global.__objectDepths[68] = 0; // obj_controls
	global.__objectDepths[69] = -3000; // obj_night
	global.__objectDepths[70] = -3001; // obj_light_control
	global.__objectDepths[71] = -3002; // obj_sparks
	global.__objectDepths[72] = 0; // obj_rampstrip
	global.__objectDepths[73] = 1; // obj_tree_log_horiz
	global.__objectDepths[74] = 0; // obj_cascade_sign
	global.__objectDepths[75] = 0; // obj_astro_sign
	global.__objectDepths[76] = 0; // obj_stadium_large_horiz
	global.__objectDepths[77] = 0; // obj_stadium_medium_horiz
	global.__objectDepths[78] = 0; // obj_glass_building
	global.__objectDepths[79] = 0; // obj_spaceframe_building
	global.__objectDepths[80] = 0; // obj_stadium_large_vert
	global.__objectDepths[81] = -100; // obj_tree1
	global.__objectDepths[82] = -100; // obj_tree2
	global.__objectDepths[83] = -100; // obj_tree3
	global.__objectDepths[84] = -100; // obj_tree5
	global.__objectDepths[85] = -101; // obj_crowd_vert_left
	global.__objectDepths[86] = -150; // obj_tyre_span
	global.__objectDepths[87] = -100; // obj_elevate_beam
	global.__objectDepths[88] = 10; // obj_person


	global.__objectNames[0] = "obj_main";
	global.__objectNames[1] = "obj_starting_grid";
	global.__objectNames[2] = "obj_path";
	global.__objectNames[3] = "obj_path_point_controller";
	global.__objectNames[4] = "obj_left_path";
	global.__objectNames[5] = "obj_solid";
	global.__objectNames[6] = "obj_block";
	global.__objectNames[7] = "obj_tread";
	global.__objectNames[8] = "obj_wheel";
	global.__objectNames[9] = "obj_car";
	global.__objectNames[10] = "obj_parent_player";
	global.__objectNames[11] = "obj_parent_ai";
	global.__objectNames[12] = "obj_sportscar";
	global.__objectNames[13] = "obj_rallycar";
	global.__objectNames[14] = "obj_racingcar";
	global.__objectNames[15] = "obj_motorbike";
	global.__objectNames[16] = "obj_go_kart";
	global.__objectNames[17] = "obj_AG_ship";
	global.__objectNames[18] = "obj_truck";
	global.__objectNames[19] = "obj_tank";
	global.__objectNames[20] = "obj_ai_sportscar1";
	global.__objectNames[21] = "obj_ai_sportscar2";
	global.__objectNames[22] = "obj_ai_sportscar3";
	global.__objectNames[23] = "obj_ai_sportscar4";
	global.__objectNames[24] = "obj_ai_racingcar_parent";
	global.__objectNames[25] = "obj_ai_racingcar1";
	global.__objectNames[26] = "obj_ai_racingcar2";
	global.__objectNames[27] = "obj_ai_racingcar3";
	global.__objectNames[28] = "obj_ai_racingcar4";
	global.__objectNames[29] = "obj_ai_motorbike1";
	global.__objectNames[30] = "obj_ai_go_kart1";
	global.__objectNames[31] = "obj_ai_AG_ship1";
	global.__objectNames[32] = "obj_ai_truck1";
	global.__objectNames[33] = "obj_ai_rallycar1";
	global.__objectNames[34] = "obj_ai_tank1";
	global.__objectNames[35] = "obj_colour_ai";
	global.__objectNames[36] = "obj_target";
	global.__objectNames[37] = "obj_draw_checkpoint_car";
	global.__objectNames[38] = "obj_draw_checkpoint_ai_yellow";
	global.__objectNames[39] = "obj_car_pathPos";
	global.__objectNames[40] = "obj_ai_yellow_pathPos";
	global.__objectNames[41] = "obj_debug_messages";
	global.__objectNames[42] = "obj_GUI";
	global.__objectNames[43] = "obj_camera";
	global.__objectNames[44] = "obj_teleport";
	global.__objectNames[45] = "obj_teleport_target";
	global.__objectNames[46] = "obj_start_lights";
	global.__objectNames[47] = "obj_race_start";
	global.__objectNames[48] = "obj_explosion";
	global.__objectNames[49] = "obj_smoke";
	global.__objectNames[50] = "obj_car_select_header";
	global.__objectNames[51] = "obj_game_version";
	global.__objectNames[52] = "obj_game_information";
	global.__objectNames[53] = "obj_rallycar_option";
	global.__objectNames[54] = "obj_go_kart_option";
	global.__objectNames[55] = "obj_motorbike_option";
	global.__objectNames[56] = "obj_racingcar_option";
	global.__objectNames[57] = "obj_truck_option";
	global.__objectNames[58] = "obj_AG_ship_option";
	global.__objectNames[59] = "obj_sportscar_option";
	global.__objectNames[60] = "obj_tank_option";
	global.__objectNames[61] = "obj_cs_menu_control";
	global.__objectNames[62] = "obj_room_controller";
	global.__objectNames[63] = "obj_continue";
	global.__objectNames[64] = "obj_restart";
	global.__objectNames[65] = "obj_exit";
	global.__objectNames[66] = "obj_pause_header";
	global.__objectNames[67] = "obj_pause_menu_controller";
	global.__objectNames[68] = "obj_controls";
	global.__objectNames[69] = "obj_night";
	global.__objectNames[70] = "obj_light_control";
	global.__objectNames[71] = "obj_sparks";
	global.__objectNames[72] = "obj_rampstrip";
	global.__objectNames[73] = "obj_tree_log_horiz";
	global.__objectNames[74] = "obj_cascade_sign";
	global.__objectNames[75] = "obj_astro_sign";
	global.__objectNames[76] = "obj_stadium_large_horiz";
	global.__objectNames[77] = "obj_stadium_medium_horiz";
	global.__objectNames[78] = "obj_glass_building";
	global.__objectNames[79] = "obj_spaceframe_building";
	global.__objectNames[80] = "obj_stadium_large_vert";
	global.__objectNames[81] = "obj_tree1";
	global.__objectNames[82] = "obj_tree2";
	global.__objectNames[83] = "obj_tree3";
	global.__objectNames[84] = "obj_tree5";
	global.__objectNames[85] = "obj_crowd_vert_left";
	global.__objectNames[86] = "obj_tyre_span";
	global.__objectNames[87] = "obj_elevate_beam";
	global.__objectNames[88] = "obj_person";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
